language: java
sudo: false

jdk:
- oraclejdk8

script: ./gradlew build

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - oracle-java8-installer
      
after_success:
  - bash <(curl -s https://codecov.io/bash)
